### ISSUE TITLE
Multiple Chartlabels overflow

### ISSUE THREAD

**Issue by renedlog** [PandaScience/FortySecondsCV#15]
![image](https://user-images.githubusercontent.com/14824710/71716690-dc186a80-2e15-11ea-9d73-7d36c53a0a96.png)
seems like multiple chartlabels overflow the first column

**Comment by renedlog** [comment]
A small fix for everyone with the same problem is a "minipage"
e.g.:
```
\begin{minipage}{\linewidth}
	          \chartlabel{Rasa}\chartlabel{Pandas}\chartlabel{Google Cloud}\chartlabel{Neo4j}
\end{minipage}
```

**Comment by PandaScience** [comment]
Yep, nice one. I did not restrict the sidebar content with anything like a minipage, so that the user can freely "overflow" on demand. The aboutme, barskill, membership etc. commands are, however, constructed in a way they can't become larger than the sidebar. The correct length for the minipage should be `\sidebartextwidth`. 
I will add a `sidebarminipage` environment to fix that behavior if required.

Edit: Actually, I use a textblock environment for the sidebar, so pure text should be wrapped. This is why `\linewidth` also works for you. :wink:
