### ISSUE TITLE
Not compiling so I am unable to use the template

### ISSUE THREAD

**Issue by gm91dev** [PandaScience/FortySecondsCV#32]
Hi,

Thanks for sharing this useful CV which I find very compact and well-done. Unfortunately I cannot compile the file and continuously getting the following error:

```
eso-pic.sty
188
Undefined control sequence.
<argument> \nointerlineskip \AddToHook 
                            {shipout/background}{\put (0,\ESO@yoffsetI ){\ESO@H
l.188 }

```

Please consider I am using TeXworks, just downloaded the latest version and tried both with LuaLaTex and XeLaTex both I get the same erro.
Can you help me?
Thanks

**Comment by PandaScience** [comment]
Hi. I just tried TeXworks on my machine and it works perfectly for all compilers. However, this is not surprising since TeXworks is only an editor and under the hood it utilizes the compilers you have installed separately on your system, e.g. via TeXlive or MikTeX (Windows).

Without further information it's hard to tell. My guess is that your LaTeX distribution needs to be updated.
You can use `\listfiles` in the preamble and then look at the log file.

For me it gives
> eso-pic.sty    2020/10/14 v3.0a eso-pic (RN)

**Comment by gm91dev** [comment]
Thanks for your quick reply. Sorry if I missed some info. Yes, I am using Windows and I have downloaded the latest bundle of TeXworks (http://www.tug.org/texworks/).  And I am using MikTeX, I have just checked that. Do you mean I should open the Update Manager and update all the packages or reinstall MikTeX from scracth? 
Thanks again

**Comment by PandaScience** [comment]
Updating should be sufficient if it is indeed a version problem.

**Comment by gm91dev** [comment]
I confirm I have reinstalled MikTeX (the latest version) and it works now.
Thank you very much for your help. Appreciated

**Comment by gm91dev** [comment]
Reinstalling MikTeX was fine and solved the issue.
