### ISSUE TITLE
How to make \cvtable split in two pages

### ISSUE THREAD

**Issue by Elfengour** [PandaScience/FortySecondsCV#39]
Allow tabular environment to break over more than one page.

**Comment by PandaScience** [comment]
Hi. Sorry for the late reply. I've tried a few things but eventually ended up with changing the `cvtable` code and use the `tabu` package. Unfortunately this adds additional space between headings and tables so that I also had to introduce a small hack as well.

Please try with the version from [this branch](https://github.com/PandaScience/FortySecondsCV/tree/feature/table-pagebreak).
