### ISSUE TITLE
Adding zoom, xshift and yshift to the profile picture.

### ISSUE THREAD

**Issue by ifokkema** [PandaScience/FortySecondsCV#6]
Hi there again,
I wanted to be able to use a ready made profile picture without needing to edit it to make it fit well for this template, especially because it would be some trial and error which is more conveniently done in LaTeX itself. As such, I implemented options to zoom, xshift and yshift the profile picture. I haven't made a PR yet because I first wanted your opinion about it, and also because it's built on top of my previous branch which still has its PR (#4) open.

Have a look whenever you have time:
https://github.com/ifokkema/FortySecondsCV/compare/feat/profilecircle...ifokkema:feat/profilePicOptions

If you're interested in including this code, I can create a PR after #4 gets merged :wink:

**Comment by PandaScience** [comment]
Great! I think this is a very useful feature. Since #4 is merged, you can create a PR for this now. However, please keep the 80 character limit (notably in the definitions of the two profilepic styles).

Unfortunately, zoom will not work as one naïvely would expect for the rounded corners style. If you like, you can fix this as part of the PR, otherwise I will figure it out in a later commit.

**Comment by ifokkema** [comment]
Thank you!
I didn't notice the zoom problem in `profileroundedcorners`, oops! I fixed that, applied the 80 char line limit, and created PR #7.
Whenever you have time :)

**Comment by ifokkema** [comment]
Oh, by the way, I noticed the indentation was a mix of mostly tabs and here and there spaces. Also, here and there lines end in spaces and my IDE has itchy fingers to fix this. Shall I let it?

**Comment by PandaScience** [comment]
Sure, go ahead. Main reason for this is that I still haven't found a good, easy to use and easy to setup latex linter and style-checker which is also compatible with vim or at least usable as git pre-commit hook (lacheck produces too many false-positives). This, in turn, is probably because there is no such thing as pep8 for latex - at least I don't know of any. So, let me know if you find one ;-).
Though...I could have indeed let lacheck and chktex have a look on the code more frequently.

For now, I basically try to use a 80 char limit and tabs for indentation as consistently as possible.
